services:
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq-dev
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq/log
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  rabbitmq-data:
  rabbitmq-logs:
