version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-dev
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend

volumes:
  rabbitmq-data:
  rabbitmq-logs:

networks:
  backend:
    name: micro__services_network
    external: true
